[package]
name = "structs-playground"
version = "0.1.0"
authors = ["Emilio Cobos Ãlvarez <emilio@crisal.io>"]
publish = false

[build-dependencies]
bindgen = "0.33.0"
gcc = "0.3"

[dependencies]
cssparser = "0.23.0"
